name: backend ci-cd

on:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Registry Login
        uses: docker/login-action@v3
        with:
          registry: registry.${{ secrets.SERVER_HOST }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}


      # 우선 테스트 생략
      # 빌드 후 푸시
      - name: Build and Push Image
        run: |
          export BE_PORT=8080
          echo "${{ secrets.APP_YML }}" > ./src/main/resources/application-prod.yml
          docker build -t registry.${{ secrets.SERVER_HOST }}/community-be:latest .
          docker push registry.${{ secrets.SERVER_HOST }}/community-be:latest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: set-up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa  ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << EOF
            cd /home/${{ secrets.SERVER_USER }}/.ssh
            ssh -i ~/${{ secrets.TUNNELING_KEY}}  ${{ secrets.TUNNELING_SERVER_USER }}@${{ secrets.TUNNELING_SERVER_HOST }} << EOF
              docker compose pull community-be
              docker compose up -d community-be
            EOF
          EOF
            
          
          
          
