name: backend ci-cd

on:
  push:
    branches:
      - main
      - develop

jobs:
  call-tests:
    uses: 100-hours-a-week/3-jehyeok-yu-community-BE/.github/workflows/ci.yml@develop

  build_push:
    needs: call-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Registry Login
        uses: docker/login-action@v3
        with:
          registry: registry.${{ secrets.SERVER_HOST }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}


      # 우선 테스트 생략
      # 빌드 후 푸시
      - name: Build and Push Image
        run: |
          export BE_PORT=8080
          echo "${{ secrets.APP_YML }}" > ./src/main/resources/application-prod.yml
          docker build -t registry.${{ secrets.SERVER_HOST }}/community-be:latest .
          docker push registry.${{ secrets.SERVER_HOST }}/community-be:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_push
    steps:
      - name: set-up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa  ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << OUTER
            cd /home/${{ secrets.SERVER_USER }}
            ssh -i ~/${{ secrets.TUNNELING_KEY }}  ${{ secrets.TUNNELING_SERVER_USER }}@${{ secrets.TUNNELING_SERVER_HOST }} << INNER
              cd /home/${{ secrets.TUNNELING_SERVER_USER }}/compose/app
              echo "${{ secrets.DOCKER_TOKEN }}" | docker login registry.${{ secrets.SERVER_HOST}} -u "${{ secrets.DOCKER_USER }}" --password-stdin \
                || {echo "레지스트리 로그인 실패"; exit 1;}
              docker compose pull community-be \
                || {echo "레지스트리에서 이미지 pull 실패"; exit 1;}
              docker compose up -d community-be \
                || {echo "컨테이너 실행 실패"; exit 1;}
          INNER
          OUTER
            
          
          
          
